# tasks:
#   - init: |
#       sudo apt-get update -y && \
#       sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev -y && \
#       wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.3.7-stable.tar.xz -P /workspace/flutter_dev && \
#       cd /workspace/flutter_dev && \
#       echo PATH="$PATH:`pwd`/flutter/bin" >> /home/gitpod/.bashrc && \
#       tar xf flutter_linux_3.3.7-stable.tar.xz
#     command: flutter run -d web-server --web-port=8080

# ports:
#   - port: 8080
#     onOpen: open-preview

# -----------------------------------------
image:
  file: .gitpod.Dockerfile

tasks:
- init: >
    flutter run -d web-server --no-resident # prebuilds the app
  command: >
    flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0
ports:
- port: 8080
  onOpen: open-preview