tasks:
  - init: |
      sudo apt-get update && \
      sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev && \
      wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.3.7-stable.tar.xz && \
      tar xf ~/Downloads/flutter_linux_3.3.7-stable.tar.xz && \
      export PATH="$PATH:`pwd`/flutter/bin"